CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users
(
id INTEGER PRIMARY key,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
unique (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT OR  IGNORE INTO telegram_users VALUES (?,?,?,?,?)
"""
SELECT_USERS = """
SELECT * FROM telegram_users
"""